# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Meteor Easy-Search'
tagline:          'Search package for Meteor'
description:      'Easy-to-use search with Blaze Components and Elastic Search Support'
url:              http://matteodem.github.io
baseurl:          /meteor-easy-search/

author:
  name:           'Matteo De Micheli'
  url:            https://github.com/matteodem

# Custom vars
version:          1.4.3
download:         https://github.com/matteodem/meteor-easy-search/archive/master.zip

github:
  repo:           https://github.com/matteodem/meteor-easy-search
